language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

sudo: false

env:
  PYTHONPATH: lib:test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint lib/ test/
#- kodi-addon-checker . --branch=krypton
#- kodi-addon-checker . --branch=leia
- proxy.py &
- coverage run -m unittest discover
- coverage run -a default.py

after_success:
- codecov
